#! /bin/sh
vimrc="/home/polluticorn/.config/nvim/init.vim"
bashrc="/home/polluticorn/.bashrc"
ith="/home/polluticorn/.config/i3/"
ithb="/home/polluticorn/.config/i3blocks/"
xdef="/home/polluticorn/.Xdefaults"
vimplugins="/home/polluticorn/.vim/"
keyRemaps="/home/polluticorn/.scripts/keyRemaps"
tmuxconf="/home/polluticorn/.tmux.conf"
scripts="/home/polluticorn/.scripts/"

cp    $vimrc      .
cp    $bashrc     .
cp    $xdef       .
cp    $keyRemaps  . 
cp    $tmuxconf   .
cp -R $ith        .
cp -R $ithb       .
cp -R $vimplugins .
cp -R $scripts    .
